name: willhays
favicon: null
layout_spectrum: 0.72433
typography_spectrum: 0.26004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#919191'
    - '#434343'
    - '#f9f9f9'
    - '#cecece'
  brandStrength: 0.6875
  lightness: 0.6047666382510215
  saturation: 0.5
  rhythmicContrast: 0.9800057078246027
purpose: []
