name: willhays
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26004
title: Testing out how well robots can design.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe0e2'
    - '#2c2c2a'
    - '#707070'
    - '#5a5a5a'
    - '#979797'
  brandStrength: 0.6875
  lightness: 0.6047666382510215
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
