name: willhays
favicon: null
layout_spectrum: 0.52344
typography_spectrum: 0.26004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000201'
    - '#e3dfd5'
    - '#720206'
    - '#94988b'
    - '#9c5d45'
  brandStrength: 0.3125
  lightness: 0.6047666382510215
  saturation: 0.5
  rhythmicContrast: 0.9800057078246027
purpose: []
