name: willhays
favicon: null
layout_spectrum: 0.50781
typography_spectrum: 0.26004
title: Testing out how well robots can design.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a0a8b3'
    - '#f6f5fa'
    - '#68707b'
    - '#00a0bf'
  brandStrength: 0.6875
  lightness: 0.6047666382510215
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
